# Generated by Django 2.0 on 2018-11-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotLine', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gzh', models.ImageField(upload_to='')),
                ('wx', models.ImageField(upload_to='')),
            ],
        ),
    ]
