# Generated by Django 2.0 on 2018-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181126_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='address',
            field=models.CharField(max_length=1000, null=True, verbose_name='公司地址'),
        ),
    ]
