# Generated by Django 2.0 on 2018-11-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lunbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='anli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='案例名字')),
                ('intro', models.CharField(max_length=2000, null=True, verbose_name='案例简介')),
                ('img', models.ImageField(upload_to='imgs', verbose_name='背景图片')),
            ],
            options={
                'verbose_name': '经典案例',
                'verbose_name_plural': '经典案例',
            },
        ),
    ]
