# Generated by Django 2.0 on 2018-11-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_anli'),
    ]

    operations = [
        migrations.CreateModel(
            name='muban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs', verbose_name='模板图片')),
            ],
            options={
                'verbose_name': '模板图片',
                'verbose_name_plural': '模板图片',
            },
        ),
    ]
