# Generated by Django 2.0 on 2018-11-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_muban'),
    ]

    operations = [
        migrations.CreateModel(
            name='fangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='方案标题')),
                ('intro', models.CharField(max_length=2000, null=True, verbose_name='方案简介')),
                ('img', models.ImageField(upload_to='imgs', verbose_name='图片')),
            ],
            options={
                'verbose_name': '解决方案',
                'verbose_name_plural': '解决方案',
            },
        ),
    ]
