# Generated by Django 2.0 on 2018-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_fangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='muban',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='模板名称'),
        ),
    ]
