# Generated by Django 2.0 on 2018-11-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinfo',
            name='hotLine',
        ),
    ]
