# Generated by Django 2.0 on 2018-11-28 01:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_baseinfo_hotline'),
    ]

    operations = [
        migrations.AddField(
            model_name='anli',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='文章详情'),
        ),
    ]
