# Generated by Django 2.0 on 2018-11-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_anli_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anli',
            name='content',
            field=models.TextField(null=True, verbose_name='文章详情'),
        ),
    ]
