# Generated by Django 2.0 on 2018-11-28 03:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181128_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anli',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='文章详情'),
        ),
    ]
