# Generated by Django 2.0 on 2018-11-28 03:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181128_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anli',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
