# Generated by Django 2.0 on 2018-11-28 08:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_muban_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='yewu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='业务介绍')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '主营业务',
                'verbose_name_plural': '主营业务',
            },
        ),
    ]
