# Generated by Django 2.0 on 2018-11-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_yewu'),
    ]

    operations = [
        migrations.AddField(
            model_name='yewu',
            name='img',
            field=models.ImageField(null=True, upload_to='imgs', verbose_name='图片'),
        ),
    ]
